### ISSUE TITLE
Relax dependency on pydantic==2.4.2

### ISSUE THREAD

**Issue by asprenger** [lastmile-ai/lastmile-utils#32]
I would like to use Python aiconfig in Ray Serve 2.9.2.

lastmile-utils has a dependency on pydantic==2.4.2.
Unfortunately ray[serve] 2.9.2 depends on pydantic!=2.0.*, !=2.1.*, !=2.2.*, !=2.3.*, !=2.4.* and <3.
This results in a dependency conflict and I can not use the libraries together.

Is there a specific reason lastmile-utils depends on pydantic==2.4.2 or would it be possible to relax the dependency to a version range, e.g. >2.0 & <3.0

**Comment by saqadri** [comment]
This should be possible, thanks for flagging @asprenger. We will look into it today and get back to you -- will confirm once we have published a patch update

**Comment by jonathanlastmileai** [comment]
@asprenger, thanks for the request. We are fairly sure we can relax the version to accommodate 2.* and anticipate publishing an update today. cc @Ankush-lastmile , @rossdanlm

**Comment by jonathanlastmileai** [comment]
@asprenger, we have relaxed the version here https://github.com/lastmile-ai/lastmile-utils/pull/33 and updated the LM utils version here: https://github.com/lastmile-ai/aiconfig/pull/1225/

We have published python-aiconfig 1.1.23 with the changes. This should now install a compatible version of pydantic (it chooses 2.6.1 for me.)

I will wait for a confirmation before closing the issue.

**Comment by asprenger** [comment]
@jonathanlastmileai 
python-aiconfig 1.1.24 solves the problem for me. 
Thanks for the quick fix!
